package com.ejemplo.inventario;

import application.service.ProductoService;
import infrastructure.adapter.persistence.ProductoRepositoryAdapter;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

@SpringBootApplication
public class InventarioApplication {

    public static void main(String[] args) {
        SpringApplication.run(InventarioApplication.class, args);
    }

    @Bean
    public ProductoService productoService(ProductoRepositoryAdapter adapter) {
        return new ProductoService(adapter);
    }
}